# Amazon Product Pricing & Review Analysis

#### . Import Libraries
#### . Load Dataset
#### . Initial Data Inspection
#### . Missing Value Handling
#### . Data Cleaning
#### . Feature Engineering
#### . Export Cleaned Dataset
#### . Summary

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## 2. Load Dataset

In [2]:
df = pd.read_csv("amazon.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

## 3. Initial Data Inspection

In [3]:
print("Initial Shape:", df.shape)
df.info()
df.isnull().sum()

Initial Shape: (1465, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

## 4. Handle Missing Values

In [4]:
# Fill missing review counts with 0
df['rating_count'] =df['rating_count'].fillna('0')

## 5. Clean Numerical Columns

In [5]:
# Remove currency symbols, commas, and percent sign

df['discounted_price'] = df['discounted_price'].astype(str).str.replace('₹', '').str.replace(',', '')

df['actual_price'] = df['actual_price'].astype(str).str.replace('₹', '').str.replace(',', '')

df['discount_percentage']= df['discount_percentage'].astype(str).str.replace('%','')

df['rating_count']= df['rating_count'].astype(str).str.replace(',','')

## 6. Convert Columns to Numeric Format

In [6]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')


df['discounted_price'] = pd.to_numeric(df['discounted_price'], errors='coerce')

df['actual_price'] = pd.to_numeric(df['actual_price'], errors='coerce')

df['discount_percentage'] = pd.to_numeric(df['discount_percentage'], errors='coerce')

df['rating_count'] = pd.to_numeric(df['rating_count'], errors='coerce')

In [7]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1465.000000,1465.000000,1465.000000,1464.000000,1465.000000
mean,3125.310874,5444.990635,47.691468,4.096585,18270.564505
std,6944.304394,10874.826864,21.635905,0.291674,42729.995315
min,39.000000,39.000000,0.000000,2.000000,0.000000
25%,325.000000,800.000000,32.000000,4.000000,1173.000000
50%,799.000000,1650.000000,50.000000,4.100000,5178.000000
75%,1999.000000,4295.000000,63.000000,4.300000,17325.000000
max,77990.000000,139900.000000,94.000000,5.000000,426973.000000

## 7. Remove Critical Missing Values , Drop duplicate values

In [8]:
df.dropna(subset=['discounted_price', 'actual_price', 'rating'], inplace=True)
df.drop_duplicates(inplace=True)

## 8. Feature Engineering

In [9]:
# Main Category Extraction
df['main_category'] = df['category'].apply(lambda x: x.split('|')[0])

In [10]:
# Savings Column
df['savings'] = df['actual_price'] - df['discounted_price']

In [11]:
# Price Segmentation
df['price_range'] = pd.cut(
    df['discounted_price'],
    bins=[0,500,2000,5000,10000,50000],
    labels=['Budget','Affordable','Mid-Range','Premium','Luxury']
)

## 9. Final Dataset Validation

In [12]:
print("Final Shape:", df.shape)
df.info()
df.describe()
df.isnull().sum()

Final Shape: (1464, 19)
<class 'pandas.core.frame.DataFrame'>
Index: 1464 entries, 0 to 1464
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1464 non-null   object
 1   product_name         1464 non-null   object
 2   category             1464 non-null   object
 3   discounted_price     1464 non-null   float64
 4   actual_price         1464 non-null   float64
 5   discount_percentage  1464 non-null   int64
 6   rating               1464 non-null   float64
 7   rating_count         1464 non-null   int64
 8   about_product        1464 non-null   object
 9   user_id              1464 non-null   object
 10  user_name            1464 non-null   object
 11  review_id            1464 non-null   object
 12  review_title         1464 non-null   object
 13  review_content       1464 non-null   object
 14  img_link             1464 non-null   object
 15  product_link         1464 non-null   object
 16  main_category        1464 non-null   object
 17  savings              1464 non-null   float64
 18  price_range          1461 non-null   category
dtypes: category(1), float64(4), int64(2), object(12)
memory usage: 218.9+ KB

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
main_category          0
savings                0
price_range            3
dtype: int64

## 10. Export Cleaned Dataset

In [13]:
df.to_csv("amazon_cleaned.csv", index=False , encoding = "utf-8")

# Key Achievements
#### Successfully completed:
#### Missing value handling
#### Currency and percentage cleaning
#### Datatype conversion
#### Duplicate removal
#### Category simplification
#### Business feature engineering
#### Price segmentation
#### SQL-ready dataset export